/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecokingboutique;

import ConexionBD.ConexionBD;
import controlador.LoginDAO;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.*;
import modelo.Usuarios;

/**
 *
 * @author victo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public static boolean entrar;
    boolean mostrarUsuarios = false;
    LoginDAO uDAO = new LoginDAO();
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogin = new javax.swing.JPanel();
        lbl_Usuario = new javax.swing.JLabel();
        tf_Usuario = new javax.swing.JTextField();
        lbl_Contraseña = new javax.swing.JLabel();
        tf_contraseña = new javax.swing.JPasswordField();
        btn_Ingresar = new javax.swing.JButton();
        lbl_imagen_login = new javax.swing.JLabel();
        btn_Ingresar1 = new javax.swing.JButton();
        lbl_Contraseña1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 470));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 470));
        getContentPane().setLayout(null);

        PanelLogin.setBackground(new java.awt.Color(204, 204, 255));
        PanelLogin.setLayout(null);

        lbl_Usuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Usuario.setText("Usuario:");
        PanelLogin.add(lbl_Usuario);
        lbl_Usuario.setBounds(60, 180, 60, 20);
        PanelLogin.add(tf_Usuario);
        tf_Usuario.setBounds(60, 210, 170, 30);

        lbl_Contraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Contraseña.setText("Contraseña:");
        PanelLogin.add(lbl_Contraseña);
        lbl_Contraseña.setBounds(60, 250, 90, 20);
        PanelLogin.add(tf_contraseña);
        tf_contraseña.setBounds(60, 280, 170, 30);

        btn_Ingresar.setText("INGRESAR");
        btn_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarActionPerformed(evt);
            }
        });
        PanelLogin.add(btn_Ingresar);
        btn_Ingresar.setBounds(100, 320, 90, 30);

        lbl_imagen_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.png"))); // NOI18N
        PanelLogin.add(lbl_imagen_login);
        lbl_imagen_login.setBounds(90, 40, 110, 140);

        btn_Ingresar1.setText("REGISTRAR");
        btn_Ingresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ingresar1ActionPerformed(evt);
            }
        });
        PanelLogin.add(btn_Ingresar1);
        btn_Ingresar1.setBounds(90, 390, 110, 30);

        lbl_Contraseña1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Contraseña1.setText("¿No tienes usuario?");
        PanelLogin.add(lbl_Contraseña1);
        lbl_Contraseña1.setBounds(80, 360, 130, 20);

        getContentPane().add(PanelLogin);
        PanelLogin.setBounds(0, 0, 300, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarActionPerformed
       Connection c = ConexionBD.getConexion();
        if (verificar()) {
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    if (mostrarUsuarios) {
                        VentanaEmpleadosAltas VEA = new VentanaEmpleadosAltas();
                        VEA.setVisible(true);
                        dispose();
                    } else {
                        VentanaEmpleadosAltas VEA = new VentanaEmpleadosAltas();
                        VEA.setVisible(true);
                        dispose();
                    }
                }
            });
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "El nombre de usuario o la contraseña son incorrectos");
        }
    }//GEN-LAST:event_btn_IngresarActionPerformed

    private void btn_Ingresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ingresar1ActionPerformed
        Register Reg = new Register();
        Reg.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_Ingresar1ActionPerformed
public boolean verificar() {
    try {
        ArrayList<Usuarios> listaUsuarios = uDAO.buscarUsuario("SELECT * FROM usuarios WHERE usuario = '" + tf_Usuario.getText()+"'");
        uDAO.setFiltro("SELECT * FROM usuarios WHERE usuario = '"+tf_Usuario.getText()+"'");

        Thread hilo = new Thread(uDAO);
        hilo.start();
        
        // Esperar a que el hilo termine antes de continuar
        hilo.join();

        if (listaUsuarios.size()!=0 && entrar) {
            Usuarios usuario = listaUsuarios.get(0);
            return usuario.getContrasena().equals(tf_contraseña.getText());
        } else {
            return false;
        }

    } catch (InterruptedException | NullPointerException e) {
        e.printStackTrace();
    }

    return true;
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JButton btn_Ingresar;
    private javax.swing.JButton btn_Ingresar1;
    private javax.swing.JLabel lbl_Contraseña;
    private javax.swing.JLabel lbl_Contraseña1;
    private javax.swing.JLabel lbl_Usuario;
    private javax.swing.JLabel lbl_imagen_login;
    private javax.swing.JTextField tf_Usuario;
    private javax.swing.JPasswordField tf_contraseña;
    // End of variables declaration//GEN-END:variables
}
